(define (startServer) (edu.rpi.csci.sdd.epic.webserver.WebServer:main (String[])))
(define methodsOf java.lang.Class:getDeclaredMethods)
(define fieldsOf java.lang.Class:getDeclaredFields)
(define (allSuperclasses cls::java.lang.Class)
    (do ((cl cls (java.lang.Class:getGenericSuperclass cl))
         (acc '() #1=(cons cl acc)))
        ((equal? cl java.lang.Object) #1#)
    )
)
